default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Employee
  username: postgres
  password: password


production:
  <<: *default
  database: Employee_production
  username: postgres
  password: password