default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Employee

test:
  <<: *default
  database: Employeetest

production:
  <<: *default
  database: Employee_production
  username: Employee
  password: password
